package com.permata.queue.report.engine;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.io.InputStream;
import java.util.Locale;

import javax.swing.JDialog;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

public class ReportCustomExecuteViewer extends JDialog {

	/**
	 *
	 */
	protected ReportCustomViewer viewer = null;

	/**
	 *
	 */
	private boolean isExitOnClose = true;

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(String sourceFile, boolean isXMLFile)
			throws JRException {
		this(sourceFile, isXMLFile, true);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setVisible(true);
	}

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(InputStream is, boolean isXMLFile)
			throws JRException {
		this(is, isXMLFile, true);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setVisible(true);
	}

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(JasperPrint jasperPrint) {
		this(jasperPrint, true);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setVisible(true);
	}

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(String sourceFile, boolean isXMLFile,
			boolean isExitOnClose) throws JRException {
		this(sourceFile, isXMLFile, isExitOnClose, null);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setVisible(true);

	}

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(InputStream is, boolean isXMLFile,
			boolean isExitOnClose) throws JRException {
		this(is, isXMLFile, isExitOnClose, null);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setVisible(true);

	}

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(JasperPrint jasperPrint,
			boolean isExitOnClose) {
		this(jasperPrint, isExitOnClose, null);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setVisible(true);
	}

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(String sourceFile, boolean isXMLFile,
			boolean isExitOnClose, Locale locale) throws JRException {
		if (locale != null)
			setLocale(locale);

		this.isExitOnClose = isExitOnClose;

		initComponents();

		this.viewer = new ReportCustomViewer(sourceFile, isXMLFile, locale);
		this.pnlMain.add(this.viewer, BorderLayout.CENTER);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setVisible(true);

	}

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(InputStream is, boolean isXMLFile,
			boolean isExitOnClose, Locale locale) throws JRException {
		if (locale != null)
			setLocale(locale);

		this.isExitOnClose = isExitOnClose;

		initComponents();

		this.viewer = new ReportCustomViewer(is, isXMLFile, locale);
		this.pnlMain.add(this.viewer, BorderLayout.CENTER);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setVisible(true);

	}

	/** Creates new form JasperViewer */
	public ReportCustomExecuteViewer(JasperPrint jasperPrint,
			boolean isExitOnClose, Locale locale) {
		if (locale != null)
			setLocale(locale);

		this.isExitOnClose = isExitOnClose;

		initComponents();

		this.viewer = new ReportCustomViewer(jasperPrint, locale);
		this.pnlMain.add(this.viewer, BorderLayout.CENTER);

		// Display the frame.
		this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		this.setModal(true);
		this.setAlwaysOnTop(true);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		pnlMain = new javax.swing.JPanel();

		setTitle("JasperViewer");
		// setIconImage(new
		// javax.swing.ImageIcon(getClass().getResource("/net/sf/jasperreports/view/images/jricon.GIF")).getImage());
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm();
			}
		});

		pnlMain.setLayout(new java.awt.BorderLayout());

		getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

		pack();

		Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
		java.awt.Dimension screenSize = toolkit.getScreenSize();
		int screenResolution = toolkit.getScreenResolution();
		float zoom = ((float) screenResolution) / JRViewer.REPORT_RESOLUTION;

		int height = (int) (550 * zoom);
		if (height > screenSize.getHeight()) {
			height = (int) screenSize.getHeight();
		}
		int width = (int) (750 * zoom);
		if (width > screenSize.getWidth()) {
			width = (int) screenSize.getWidth();
		}

		java.awt.Dimension dimension = new java.awt.Dimension(width, height);
		setSize(dimension);
		setLocation((screenSize.width - width) / 2,
				(screenSize.height - height) / 2);
	}// GEN-END:initComponents

	/** Exit the Application */
	void exitForm() {// GEN-FIRST:event_exitForm

		if (this.isExitOnClose) {
			System.exit(0);
		} else {
			this.setVisible(false);
			// this.viewer.clear();
			this.viewer = null;
			this.getContentPane().removeAll();
			this.dispose();
		}

	}// GEN-LAST:event_exitForm

	/**
	 *
	 */
	public void setZoomRatio(float zoomRatio) {
		viewer.setZoomRatio(zoomRatio);
	}

	/**
	 *
	 */
	public void setFitWidthZoomRatio() {
		viewer.setFitWidthZoomRatio();
	}

	/**
	 *
	 */
	public void setFitPageZoomRatio() {
		viewer.setFitPageZoomRatio();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		String fileName = null;
		boolean isXMLFile = false;

		for (int i = 0; i < args.length; i++) {
			if (args[i].startsWith("-XML")) {
				isXMLFile = true;
			} else if (args[i].startsWith("-F")) {
				fileName = args[i].substring(2);
			} else {
				fileName = args[i];
			}
		}

		if (fileName == null) {
			usage();
			return;
		}

		if (!isXMLFile && fileName.endsWith(".jrpxml")) {
			isXMLFile = true;
		}

		try {
			viewReport(fileName, isXMLFile);
		} catch (JRException e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

	/**
	 *
	 */
	private static void usage() {
		System.out.println("JasperViewer usage:");
		System.out.println("\tjava JasperViewer [-XML] file");
	}

	/**
	 *
	 */
	public static void viewReport(String sourceFile, boolean isXMLFile)
			throws JRException {
		viewReport(sourceFile, isXMLFile, true, null);
	}

	/**
	 *
	 */
	public static void viewReport(InputStream is, boolean isXMLFile)
			throws JRException {
		viewReport(is, isXMLFile, true, null);
	}

	/**
	 *
	 */
	public static void viewReport(JasperPrint jasperPrint) {
		viewReport(jasperPrint, true, null);
	}

	/**
	 *
	 */
	public static void viewReport(String sourceFile, boolean isXMLFile,
			boolean isExitOnClose) throws JRException {
		viewReport(sourceFile, isXMLFile, isExitOnClose, null);
	}

	/**
	 *
	 */
	public static void viewReport(InputStream is, boolean isXMLFile,
			boolean isExitOnClose) throws JRException {
		viewReport(is, isXMLFile, isExitOnClose, null);
	}

	/**
	 *
	 */
	public static void viewReport(JasperPrint jasperPrint, boolean isExitOnClose) {
		viewReport(jasperPrint, isExitOnClose, null);
	}

	/**
	 *
	 */
	public static void viewReport(String sourceFile, boolean isXMLFile,
			boolean isExitOnClose, Locale locale) throws JRException {
		JasperViewer jasperViewer = new JasperViewer(sourceFile, isXMLFile,
				isExitOnClose, locale);
		jasperViewer.setVisible(true);
	}

	/**
	 *
	 */
	public static void viewReport(InputStream is, boolean isXMLFile,
			boolean isExitOnClose, Locale locale) throws JRException {
		JasperViewer jasperViewer = new JasperViewer(is, isXMLFile,
				isExitOnClose, locale);
		jasperViewer.setVisible(true);
	}

	/**
	 *
	 */
	public static void viewReport(JasperPrint jasperPrint,
			boolean isExitOnClose, Locale locale) {
		JasperViewer jasperViewer = new JasperViewer(jasperPrint,
				isExitOnClose, locale);
		jasperViewer.setVisible(true);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel pnlMain;
	// End of variables declaration//GEN-END:variables
}
